begin;

create table if not exists public.public_holidays (
  id bigint generated by default as identity primary key,
  region text not null,
  holiday_date date not null,
  name text not null,
  source text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint public_holidays_region_date_key unique (region, holiday_date)
);

alter table public.public_holidays enable row level security;

drop policy if exists "Public read holidays" on public.public_holidays;
create policy "Public read holidays"
  on public.public_holidays for select
  to anon, authenticated
  using (true);

grant select on public.public_holidays to anon, authenticated;

alter table public.salons
  add column if not exists holiday_region text default 'DE-BE',
  add column if not exists block_public_holidays boolean default true;

update public.salons
set holiday_region = coalesce(nullif(holiday_region, ''), 'DE-BE'),
    block_public_holidays = coalesce(block_public_holidays, true)
where holiday_region is null
   or holiday_region = ''
   or block_public_holidays is null;

alter table public.salons
  alter column holiday_region set default 'DE-BE',
  alter column holiday_region set not null,
  alter column block_public_holidays set default true,
  alter column block_public_holidays set not null;

create or replace function public.easter_sunday(p_year integer)
returns date
language plpgsql
immutable
strict
set search_path = public
as $$
declare
  a integer := p_year % 19;
  b integer := p_year / 100;
  c integer := p_year % 100;
  d integer := b / 4;
  e integer := b % 4;
  f integer := (b + 8) / 25;
  g integer := (b - f + 1) / 3;
  h integer;
  i integer := c / 4;
  k integer := c % 4;
  l integer;
  m integer;
  month_number integer;
  day_number integer;
begin
  h := (19 * a + b - d - g + 15) % 30;
  l := (32 + 2 * e + 2 * i - h - k) % 7;
  m := (a + 11 * h + 22 * l) / 451;
  month_number := (h + l - 7 * m + 114) / 31;
  day_number := ((h + l - 7 * m + 114) % 31) + 1;
  return make_date(p_year, month_number, day_number);
end;
$$;

create or replace function public.generate_berlin_public_holidays(
  p_start_year integer,
  p_end_year integer
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  holiday_year integer;
  easter date;
begin
  if p_start_year < 1900 or p_end_year > 2200 or p_end_year < p_start_year then
    raise exception 'Invalid holiday year range';
  end if;

  for holiday_year in p_start_year..p_end_year loop
    easter := public.easter_sunday(holiday_year);

    insert into public.public_holidays (region, holiday_date, name, source)
    select 'DE-BE', holiday.holiday_date, holiday.name, 'rule:DE-BE'
    from (
      values
        (make_date(holiday_year, 1, 1), 'Neujahr'),
        (make_date(holiday_year, 3, 8), 'Internationaler Frauentag'),
        (easter - 2, 'Karfreitag'),
        (easter + 1, 'Ostermontag'),
        (make_date(holiday_year, 5, 1), 'Tag der Arbeit'),
        (easter + 39, 'Christi Himmelfahrt'),
        (easter + 50, 'Pfingstmontag'),
        (make_date(holiday_year, 10, 3), 'Tag der Deutschen Einheit'),
        (make_date(holiday_year, 12, 25), '1. Weihnachtstag'),
        (make_date(holiday_year, 12, 26), '2. Weihnachtstag')
    ) as holiday(holiday_date, name)
    on conflict (region, holiday_date) do update
      set name = excluded.name,
          source = excluded.source,
          updated_at = now();
  end loop;
end;
$$;

revoke all on function public.generate_berlin_public_holidays(integer, integer) from public;
revoke all on function public.easter_sunday(integer) from public;

select public.generate_berlin_public_holidays(
  extract(year from current_date)::integer,
  extract(year from current_date)::integer + 3
);

create or replace function public.get_effective_day_settings(
  p_salon_slug text,
  p_setting_date date
)
returns table (
  setting_date date,
  open_time time,
  close_time time,
  is_blocked_day boolean,
  is_public_holiday boolean,
  holiday_name text,
  has_manual_override boolean
)
language sql
stable
security definer
set search_path = public
as $$
  select
    p_setting_date,
    coalesce(settings.open_time, '10:00'::time),
    coalesce(
      settings.close_time,
      case when extract(isodow from p_setting_date) = 6 then '17:00'::time else '18:00'::time end
    ),
    case
      when settings.salon_id is not null then settings.is_blocked_day
      when extract(isodow from p_setting_date) = 7 then true
      when salon.block_public_holidays and holiday.holiday_date is not null then true
      else false
    end,
    holiday.holiday_date is not null,
    holiday.name,
    settings.salon_id is not null
  from public.salons salon
  left join public.shop_day_settings settings
    on settings.salon_id = salon.id
   and settings.setting_date = p_setting_date
  left join public.public_holidays holiday
    on holiday.region = salon.holiday_region
   and holiday.holiday_date = p_setting_date
  where salon.slug = p_salon_slug
    and salon.is_active = true;
$$;

revoke all on function public.get_effective_day_settings(text, date) from public;
grant execute on function public.get_effective_day_settings(text, date) to anon, authenticated;

-- Booking creation repeats the effective holiday/day-settings check server-side.

create or replace function public.create_public_booking(
  p_salon_slug text,
  p_service_id text,
  p_appointment_date date,
  p_start_time time,
  p_gender text,
  p_name text,
  p_phone text,
  p_email text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_salon_id uuid;
  v_timezone text := 'Europe/Berlin';
  v_customer_id uuid := gen_random_uuid();
  v_appointment_id uuid := gen_random_uuid();
  v_duration integer;
  v_booked_slots smallint[];
  v_occupied_slots time[];
  v_end_time time;
  v_open_time time := '10:00';
  v_close_time time := '18:00';
  v_blocked_day boolean := false;
  v_staff_lane_id uuid;
  v_lane_key text;
begin
  select salon.id, coalesce(salon.timezone, 'Europe/Berlin')
    into v_salon_id, v_timezone
  from public.salons salon
  where salon.slug = p_salon_slug and salon.is_active = true;

  if v_salon_id is null then raise exception 'Unknown salon'; end if;

  select service.duration_minutes, service.booked_slots
    into v_duration, v_booked_slots
  from public.services service
  where service.id = p_service_id
    and service.salon_id = v_salon_id
    and service.is_active = true;

  if v_duration is null then raise exception 'Unknown or inactive service'; end if;

  select settings.open_time, settings.close_time, settings.is_blocked_day
    into v_open_time, v_close_time, v_blocked_day
  from public.get_effective_day_settings(p_salon_slug, p_appointment_date) settings;

  if not found then raise exception 'Day settings are unavailable'; end if;

  v_end_time := (p_start_time + make_interval(mins => v_duration))::time;
  select array_agg(
    (p_start_time + make_interval(mins => (slot_number - 1) * 30))::time
    order by slot_number
  ) into v_occupied_slots
  from unnest(v_booked_slots) as slot_number;

  if p_appointment_date < (now() at time zone v_timezone)::date then raise exception 'Cannot book a past date'; end if;
  if length(trim(p_name)) < 2 or length(trim(p_name)) > 50 or trim(p_name) ~ '^[0-9]+$' then raise exception 'Invalid customer name'; end if;
  if p_gender not in ('male', 'female') then raise exception 'Invalid gender'; end if;
  if length(trim(p_phone)) < 3 or length(trim(p_phone)) > 50 then raise exception 'Invalid phone'; end if;
  if length(trim(p_email)) > 50 or trim(p_email) !~* '^[^@\s]+@[^@\s]+\.[^@\s]+$' then raise exception 'Invalid email'; end if;
  if v_blocked_day then raise exception 'This day is not available'; end if;
  if public.time_to_minutes(p_start_time) % 30 <> 0 then raise exception 'Start time must use 30 minute increments'; end if;
  if v_end_time <= p_start_time or p_start_time < v_open_time or v_end_time > v_close_time then raise exception 'Booking is outside working hours'; end if;

  perform pg_advisory_xact_lock(
    hashtextextended(v_salon_id::text || ':' || p_appointment_date::text, 0)
  );

  select lane.id, lane.lane_key
    into v_staff_lane_id, v_lane_key
  from public.staff_lanes lane
  join public.salon_staff staff on staff.id = lane.staff_id
  where lane.salon_id = v_salon_id
    and lane.is_active = true
    and staff.is_active = true
    and staff.accepts_online_bookings = true
    and not exists (
      select 1 from public.schedule_entries entry
      where entry.staff_id = staff.id
        and entry.schedule_date = p_appointment_date
        and entry.status = 'active'
        and entry.occupied_slots && v_occupied_slots
    )
  order by staff.sort_order, lane.sort_order
  limit 1;

  if v_staff_lane_id is null then raise exception 'No available staff lane for this service'; end if;

  if (
    select count(*)
    from public.appointments appointment
    join public.customers customer on customer.id = appointment.customer_id
    where appointment.salon_id = v_salon_id
      and appointment.created_at > now() - interval '10 minutes'
      and (
        lower(customer.email) = lower(trim(p_email))
        or regexp_replace(customer.phone, '\s+', '', 'g') = regexp_replace(trim(p_phone), '\s+', '', 'g')
      )
  ) >= 3 then raise exception 'Too many booking attempts'; end if;

  insert into public.customers (id, salon_id, name, phone, email, gender)
  values (v_customer_id, v_salon_id, trim(p_name), trim(p_phone), lower(trim(p_email)), p_gender);

  insert into public.appointments (
    id, salon_id, customer_id, service_id, appointment_date,
    start_time, end_time, occupied_slots, lane_key, status
  ) values (
    v_appointment_id,
    v_salon_id,
    v_customer_id,
    p_service_id,
    p_appointment_date,
    (p_appointment_date::timestamp + p_start_time) at time zone v_timezone,
    (p_appointment_date::timestamp + v_end_time) at time zone v_timezone,
    v_occupied_slots,
    v_lane_key,
    'confirmed'
  );

  return v_appointment_id;
end;
$$;

revoke all on function public.create_public_booking(text, text, date, time, text, text, text, text) from public;
grant execute on function public.create_public_booking(text, text, date, time, text, text, text, text)
  to anon, authenticated;

comment on column public.salon_staff.accepts_online_bookings is
  'Public availability only offers times where all active lanes of an enabled staff member are free.';

create extension if not exists pg_cron;

do $schedule$
declare
  v_job_id bigint;
begin
  for v_job_id in
    select jobid from cron.job where jobname = 'openslot-public-holidays-yearly'
  loop
    perform cron.unschedule(v_job_id);
  end loop;

  perform cron.schedule(
    'openslot-public-holidays-yearly',
    '15 2 2 1 *',
    $job$select public.generate_berlin_public_holidays(
      extract(year from current_date)::integer,
      extract(year from current_date)::integer + 3
    );$job$
  );
end;
$schedule$;

commit;
